### ISSUE TITLE
Toggle with keyboard?

### ISSUE THREAD

**Issue by StefanScherer** [freetonik/vscode-dnts#5]
This extension looks promising. I'm coming from Atom and use https://atom.io/packages/theme-switcher where I can just press eg. `F12` to toggle between both themes.
Is this possible with VSCode and this extension already?

**Comment by freetonik** [comment]
Not with a single press, only through a command palette at the moment. Feel free to make a pull request and add a hotkey ;-)

**Comment by StefanScherer** [comment]
Yes, I thought about it. But I looked further through the marketplace and found what does what I need (jewsofhazard.quick-theme-flip). Thanks for your time!
