### ISSUE TITLE
[request] bind a key for theme toggling

### ISSUE THREAD

**Issue by atnbueno** [freetonik/vscode-dnts#7]
I was going to do the modification myself and do a PR, but I see the version in this repository is 0.0.1 while [the one in Marketplace is 0.1.0](https://marketplace.visualstudio.com/items?itemName=freetonik.day-night-theme-switcher) :-/

For now I'm using [Kevin Latusinski's _Theme Switcher for VS Code_](https://marketplace.visualstudio.com/items?itemName=latusinski.theme-switcher), and while I prefer your theme selection via configuration, that `Ctrl+Alt+T` is soooooo intuitive :-)

**Comment by freetonik** [comment]
Done! You can update the extension now. The default keybinding is `ctrl+alt+t` on Windows and Linux, `cmd+alt+t` on macOS.

**Comment by atnbueno** [comment]
Thanks a lot for the fast update :-)

One tiny problem: if the current theme is not either `dayNightThemeSwitcher.dayTheme` nor `dayNightThemeSwitcher.nightTheme`, the keybinding does nothing.

I'm not sure what would be the best solution. Perhaps a warning message? An initial offer of theme pairs?

**Comment by freetonik** [comment]
@gregflynn what do you think (since you've implemented the toggle functionality in the first place)? I think the toggle should work regardless and switch to either day or night theme from any theme.

**Comment by gregflynn** [comment]
Yep I agree it doing nothing by default was an oversight, and is a poor experience. I'll do two things:
- If neither are set and you hit toggle, set dark theme (I'm usually in dark theme, I'm biased here)
- Expose another setting like `toggleDefaultDark` defaulting to `true` for the above reason, but configurable

I'll see if I can whip this up later tonight, shouldn't be an involved change
